# Generated by Django 4.1.1 on 2022-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
