# Generated by Django 4.1.1 on 2022-09-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postagem_valor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postagem',
            new_name='Produto',
        ),
    ]
